In [66]:
import pandas as pd
import numpy as np

In [67]:
df = pd.read_csv("klinikbew.csv")

In [68]:
df.describe().transpose()

,count,unique,top,freq
NameKlinik,3354,24,Diana Klinik-Fachklinik für Physikalische Medizin,330
Titel,3352,3095,Sehr zufrieden,19
DatumBewertung,3354,2339,07.03.2019,6
Fachbereich,3350,35,Orthopädie,376
Erfahrungsbericht,3310,3309,Die An- und Abreise im Januar 2013 waren perfe...,2
Gesamtzufriedenheit,3354,4,star-6,1654
QualitätBeratung,3354,4,star-6,1633
MedizBehandlung,3354,4,star-6,1786
VerwaltungAblaeufe,3354,4,star-6,1257

### Missing Data

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3354 entries, 0 to 3353
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   NameKlinik           3354 non-null   object
 1   Titel                3352 non-null   object
 2   DatumBewertung       3354 non-null   object
 3   Fachbereich          3350 non-null   object
 4   Erfahrungsbericht    3310 non-null   object
 5   Gesamtzufriedenheit  3354 non-null   object
 6   QualitätBeratung     3354 non-null   object
 7   MedizBehandlung      3354 non-null   object
 8   VerwaltungAblaeufe   3354 non-null   object
dtypes: object(9)
memory usage: 236.0+ KB

In [70]:
count = df.isnull().sum().sort_values(ascending=False)
percentage = ((df.isnull().sum()/len(df)*100)).sort_values(ascending=False)
missing_data = pd.concat([count, percentage], axis=1, keys=['Count','Percentage'])

print('Percentage of missing values of the columns:')

missing_data

Percentage of missing values of the columns:

                     Count  Percentage
Erfahrungsbericht       44    1.311866
Fachbereich              4    0.119261
Titel                    2    0.059630
NameKlinik               0    0.000000
DatumBewertung           0    0.000000
Gesamtzufriedenheit      0    0.000000
QualitätBeratung         0    0.000000
MedizBehandlung          0    0.000000
VerwaltungAblaeufe       0    0.000000

Dropping the missing values

In [71]:
df = df.dropna()

In [72]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3304 entries, 0 to 3353
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   NameKlinik           3304 non-null   object
 1   Titel                3304 non-null   object
 2   DatumBewertung       3304 non-null   object
 3   Fachbereich          3304 non-null   object
 4   Erfahrungsbericht    3304 non-null   object
 5   Gesamtzufriedenheit  3304 non-null   object
 6   QualitätBeratung     3304 non-null   object
 7   MedizBehandlung      3304 non-null   object
 8   VerwaltungAblaeufe   3304 non-null   object
dtypes: object(9)
memory usage: 258.1+ KB

### Befreien von Zeilen

In [73]:
df = df.replace('\n',' ', regex=True)

In [74]:
df.head()

,NameKlinik,Titel,DatumBewertung,Fachbereich,Erfahrungsbericht,Gesamtzufriedenheit,QualitätBeratung,MedizBehandlung,VerwaltungAblaeufe
0,HEH Herzogin Elisabeth Hospital,Bewertung,09.06.2021,Chirurgie,Sehr höfliche und hilfsbereite Mitarbeiter. S...,star-6,star-6,star-6,star-6
1,HEH Herzogin Elisabeth Hospital,Weiter so HEH,09.06.2021,Chirurgie,Kann ich nur weiterempfehlen!! Sehr gutes Pfle...,star-6,star-4,star-6,star-4
2,HEH Herzogin Elisabeth Hospital,Superklinik,07.06.2021,Orthopädie,Bestens durchorganisiert.gutes Personal geht i...,star-6,star-6,star-6,star-6
3,HEH Herzogin Elisabeth Hospital,Kranken- oder Hotelzimmer?,25.05.2021,Unfallchirurgie,Bin nach einem Autounfall im HEH gewesen und h...,star-6,star-6,star-6,star-6
4,HEH Herzogin Elisabeth Hospital,Knie OP,11.05.2021,Orthopädie,Wurde bereits im Sept. 2020 am Knie operiert. ...,star-6,star-6,star-6,star-6

### Sterne
Sterne sind Texte, sollten in Zahlen geändert werden

In [75]:
# Düzenle
# np.vectorize(cleanup)(df['Gesamtzufriedenheit'])
# def cleanup(name):
  #  name = name.str.split('-').str[1]
   # return name

In [76]:
df['Gesamt'] = df['Gesamtzufriedenheit'].str.split('-').str[1]
df['QualBeratung'] = df['QualitätBeratung'].str.split('-').str[1]
df['MedBehandlung'] = df['MedizBehandlung'].str.split('-').str[1]
df['VerwalAblaeufe'] = df['VerwaltungAblaeufe'].str.split('-').str[1]

In [85]:
df[['NameKlinik', 'Erfahrungsbericht', 'Gesamt']]

,NameKlinik,Erfahrungsbericht,Gesamt
0,HEH Herzogin Elisabeth Hospital,Sehr höfliche und hilfsbereite Mitarbeiter. S...,6
1,HEH Herzogin Elisabeth Hospital,Kann ich nur weiterempfehlen!! Sehr gutes Pfle...,6
2,HEH Herzogin Elisabeth Hospital,Bestens durchorganisiert.gutes Personal geht i...,6
3,HEH Herzogin Elisabeth Hospital,Bin nach einem Autounfall im HEH gewesen und h...,6
4,HEH Herzogin Elisabeth Hospital,Wurde bereits im Sept. 2020 am Knie operiert. ...,6
...,...,...,...
3349,Diana Klinik-Fachklinik für Physikalische Medizin,"Schematisches Konzept. Man sollte sagen, was m...",6
3350,Diana Klinik-Fachklinik für Physikalische Medizin,Ich war von Maerz 2008 bis Ende April als Pati...,6
3351,Diana Klinik-Fachklinik für Physikalische Medizin,Ich hatte dort einen 7-wöchigen Aufenthalt in ...,0
3352,Diana Klinik-Fachklinik für Physikalische Medizin,"Erstmal ist es sehr wichtig zu wissen, dass de...",0
3353,Diana Klinik-Fachklinik für Physikalische Medizin,Ich war 2006 für 6 Wochen Patientin in der Dia...,4

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3304 entries, 0 to 3353
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   NameKlinik           3304 non-null   object
 1   Titel                3304 non-null   object
 2   DatumBewertung       3304 non-null   object
 3   Fachbereich          3304 non-null   object
 4   Erfahrungsbericht    3304 non-null   object
 5   Gesamtzufriedenheit  3304 non-null   object
 6   QualitätBeratung     3304 non-null   object
 7   MedizBehandlung      3304 non-null   object
 8   VerwaltungAblaeufe   3304 non-null   object
 9   Gesamt               3304 non-null   object
 10  QualBeratung         3304 non-null   object
 11  MedBehandlung        3304 non-null   object
 12  VerwalAblaeufe       3304 non-null   object
dtypes: object(13)
memory usage: 361.4+ KB

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3304 entries, 0 to 3353
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   NameKlinik           3304 non-null   object
 1   Titel                3304 non-null   object
 2   DatumBewertung       3304 non-null   object
 3   Fachbereich          3304 non-null   object
 4   Erfahrungsbericht    3304 non-null   object
 5   Gesamtzufriedenheit  3304 non-null   object
 6   QualitätBeratung     3304 non-null   object
 7   MedizBehandlung      3304 non-null   object
 8   VerwaltungAblaeufe   3304 non-null   object
 9   Gesamt               3304 non-null   object
 10  QualBeratung         3304 non-null   object
 11  MedBehandlung        3304 non-null   object
 12  VerwalAblaeufe       3304 non-null   object
dtypes: object(13)
memory usage: 361.4+ KB

In [81]:
df = df.dropna()

In [82]:
df

,NameKlinik,Titel,DatumBewertung,Fachbereich,Erfahrungsbericht,Gesamtzufriedenheit,QualitätBeratung,MedizBehandlung,VerwaltungAblaeufe,Gesamt,QualBeratung,MedBehandlung,VerwalAblaeufe
0,HEH Herzogin Elisabeth Hospital,Bewertung,09.06.2021,Chirurgie,Sehr höfliche und hilfsbereite Mitarbeiter. S...,star-6,star-6,star-6,star-6,6,6,6,6
1,HEH Herzogin Elisabeth Hospital,Weiter so HEH,09.06.2021,Chirurgie,Kann ich nur weiterempfehlen!! Sehr gutes Pfle...,star-6,star-4,star-6,star-4,6,4,6,4
2,HEH Herzogin Elisabeth Hospital,Superklinik,07.06.2021,Orthopädie,Bestens durchorganisiert.gutes Personal geht i...,star-6,star-6,star-6,star-6,6,6,6,6
3,HEH Herzogin Elisabeth Hospital,Kranken- oder Hotelzimmer?,25.05.2021,Unfallchirurgie,Bin nach einem Autounfall im HEH gewesen und h...,star-6,star-6,star-6,star-6,6,6,6,6
4,HEH Herzogin Elisabeth Hospital,Knie OP,11.05.2021,Orthopädie,Wurde bereits im Sept. 2020 am Knie operiert. ...,star-6,star-6,star-6,star-6,6,6,6,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3349,Diana Klinik-Fachklinik für Physikalische Medizin,Gute Therapie und Konzept Diese Bewertung geht...,19.11.2008,Orthopädie,"Schematisches Konzept. Man sollte sagen, was m...",star-6,star-4,star-6,star-4,6,4,6,4
3350,Diana Klinik-Fachklinik für Physikalische Medizin,Erinnerung an Diana Klinik 2 Diese Bewertung g...,12.11.2008,Psychosomatik,Ich war von Maerz 2008 bis Ende April als Pati...,star-6,star-6,star-0,star-4,6,6,0,4
3351,Diana Klinik-Fachklinik für Physikalische Medizin,Schöner Kurort - schlechte psychosomatische Kl...,13.10.2008,Psychosomatik,Ich hatte dort einen 7-wöchigen Aufenthalt in ...,star-0,star-2,star-0,star-0,0,2,0,0
3352,Diana Klinik-Fachklinik für Physikalische Medizin,Ruhe und Erholung - aber keine Therapie! Diese...,07.10.2008,Psychosomatik,"Erstmal ist es sehr wichtig zu wissen, dass de...",star-0,star-0,star-4,star-4,0,0,4,4
3353,Diana Klinik-Fachklinik für Physikalische Medizin,"Ein Super Erholungsort, aber keine Klinik für ...",03.02.2008,Psychosomatik,Ich war 2006 für 6 Wochen Patientin in der Dia...,star-4,star-2,star-2,star-4,4,2,2,4

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 3304 entries, 0 to 3353
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   NameKlinik           3304 non-null   object
 1   Titel                3304 non-null   object
 2   DatumBewertung       3304 non-null   object
 3   Fachbereich          3304 non-null   object
 4   Erfahrungsbericht    3304 non-null   object
 5   Gesamtzufriedenheit  3304 non-null   object
 6   QualitätBeratung     3304 non-null   object
 7   MedizBehandlung      3304 non-null   object
 8   VerwaltungAblaeufe   3304 non-null   object
 9   Gesamt               3304 non-null   object
 10  QualBeratung         3304 non-null   object
 11  MedBehandlung        3304 non-null   object
 12  VerwalAblaeufe       3304 non-null   object
dtypes: object(13)
memory usage: 361.4+ KB